### ISSUE TITLE
Fluidlogged Compatibility Issue

### ISSUE THREAD

**Issue by Ultimushadow** [Andrew6rant/Auto-Slabs#14]
Hey there, I've already detailed this issue here: https://github.com/Leximon/Fluidlogged/issues/13
The gist is that the client crashes when placing a slab when both mods are loaded, more detail in the linked issue report!

**Comment by Andrew6rant** [comment]
The issue here is that I set slab placement to be null on the client (because I have the server handle it). Fluidlogged tries to access the null state here: https://github.com/Leximon/Fluidlogged/blob/4b046ddd9130d632674474ccd2f0d3ef72b50deb/Common/src/main/java/de/leximon/fluidlogged/mixin/classes/SlabBlockMixin.java#L17

All Fluidlogged needs to do to avoid the crash is to not set that state on the client, I think. Alternately they could null check.

Anyways, Fluidlogged mod injects blockstates in an insanely unsafe way. I'm not going to support it.

Here's a patched jar of AutoSlabs that won't crash (it also fixes the issue where AutoSlab's keeps waterlogged state when double slabbed, whoops!). This "fixes" the issue by setting the slab placement state on both the server and the client. The reason I don't do that is partially for performance but mostly because it can cause a visual desync on slab placement when the client and the server do not agree which state to set the slab as. This mostly happens when moving quickly and placing slabs at the same time.

[autoslabs-1.1.2-fluidlogged-patch.zip](https://github.com/Andrew6rant/Auto-Slabs/files/12433215/autoslabs-1.1.2-fluidlogged-patch.zip)
(GitHub doesn't support `.jar` files, just rename `.zip` to `.jar` or download it off of Actions: https://github.com/Andrew6rant/Auto-Slabs/actions/runs/5968731632)

**Comment by Ultimushadow** [comment]
Interesting, is this why the client doesn't make a block placing animation with this mod installed? I noticed that while testing
Either way, thank you for the patch jar!! I'll see what the Fluidlogged dev says or potentially implement your proposed solution myself if I have the time
