### ISSUE TITLE
Glass panes not connecting to vertical slabs

### ISSUE THREAD

**Issue by DadoIrie** [Andrew6rant/Auto-Slabs#3]
actual behavior
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/988f04e8-ab49-482b-befa-bd3be12f7b67)

expected behavior
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/eb3543c9-1971-4dd9-a320-6ff12bfc6d1a)

if need idea/inspiration how to accomplish that check the enchanted vertical slabs mod (uses only vanilla slabs and they also need to be crafted)
your approach is much better as slabs are slabs and they should be able to be place horizontally & vertically (without the need to "craft" vertical slabs)

besides that slabs from other mods are not being placed vertically - they are being placed on the lower or higher half of the full block depending on which side being placed, because the overlay on the placed block from auto-slab is present

extra: please make vertical glass slabs work, as all the dynamical vertical slabs mod haven't managed that - they ain't transparent & a middle line is present like the slab is cut in 2

**Comment by Andrew6rant** [comment]
Legally I can't use any code from Enchanted Vertical Slabs, because it is licensed under All Rights Reserved.

Getting glass panes to connect to vertical slabs but not horizontal tags might be a bit of an issue, since connectivity is handled by tags and it is not possible to change tags depending on blockstate (they are meant to be per-block, and really, _really_, should not be changed mid-game).

Since Enchanted Vertical Slabs' vertical slabs are a separate block, I am going to assume they simply added their vertical slabs to the `minecraft:walls` tag, and did not add that tag to regular slabs.

My vertical slabs _are _ regular slabs, so I can't do that. I think I might know a way around that though, hacking into the wall connection code itself.

Also, if you could make a separate issue for the glass slab compatibility, I would be appreciative.

**Comment by DadoIrie** [comment]
and regarding any slabs from another mods - is there any additional dependency I need to add or should this work out of the box? (will open a separate issue regarding the glass slabs (if there is any) once I understand this)

**Comment by Andrew6rant** [comment]
This mod requires that the user download Fabric API.

Internally, I bundle ARRP 0.7.0 and Statement API 4.2.8. You do not need to download them, they're already included in this mod for your convenience.

**Comment by Andrew6rant** [comment]
I'm re-opening this issue until I fix this

**Comment by Andrew6rant** [comment]
![AutoSlabs_connected_glass_panes](https://github.com/Andrew6rant/Auto-Slabs/assets/57331134/e7cd0115-965f-4d2e-9e47-e25d87741fa2)

**Comment by DadoIrie** [comment]
Wonderful 🤗 
just tested it and works like a charm

**Comment by Andrew6rant** [comment]
Implemented in version 1.1.0.
